swagger: '2.0'
info:
  title: 服务端API
  description: 对接H5或者APP
  version: v1
host: localhost:9000
schemes:
  - http
basePath: /v1
produces:
  - application/json
#securityDefinitions:
#  bearer:
#    type: "apiKey"
#    name: "Authorization"
#    in: header
tags:
  - name: Auth
    description: 授权
  - name: Codes
    description: 短信验证码
  - name: Images
    description: 图片上传
  - name: Users
    description: 用户
  - name: Certs
    description: 证书申请/审批/查看
  - name: Tracs
    description: 追溯信息查询

paths:
  '/certs':
    post:
      summary: 申请证书
      consumes:
         - application/json
      parameters:
        - name: cert
          in: body
          description: 证书申请信息
          required: true
          schema:
             $ref: '#/definitions/Cert'
      tags:
        - Certs
      responses:
        201:
          description: 申请成功,等待审核

  '/certs/{id}':
    get:
      summary: 获取证书信息
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: 证书id
          type: string
          required: true
          schema:
            $ref: '#/definitions/Cert'
      tags:
        - Certs
      responses:
        '200':
          description: 查询成功

  '/certs/{id}/{status}':
    patch:
      summary: 审批证书
      consumes:
         - application/json
      parameters:
        - name: id
          in: path
          description: 证书id
          required: true
          type: string
        - name: status
          in: path
          description: 证书申请状态；0:未审核(默认) 1：审核通过 2：审核不通过
          required: true
          type: integer
      tags:
        - Certs
      responses:
        201:
          description: 服务器正常返回
          schema:
            $ref: '#/definitions/Cert'

  '/tracs/{type}':
    get:
      summary: 追溯信息查询
      consumes:
         - application/json
      parameters:
        - name: type
          in: path
          description: 0:电池厂商 1：汽车厂商 2：all(针对政府内部人员)
          required: true
          type: integer
      tags:
        - Tracs
      responses:
        200:
          description: 查询成功
          schema:
             $ref: '#/definitions/Trac'

  '/auth':
    post:
      summary: 获取授权token
      consumes:
         - application/json
      parameters:
        - name: auth
          in: body
          description: 用户信息.
          required: true
          schema:
              $ref: '#/definitions/Auth'
      tags:
        - Auth
      responses:
        201:
          description: 服务器正常返回
          schema:
            $ref: '#/definitions/Token'

  '/users':
    post:
      summary: 注册用户
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          description: 用户信息
          required: true
          schema:
            $ref: '#/definitions/User'
      tags:
        - Users
      responses:
        '201':
          description: 注册成功

  '/users/{id}':
    get:
      summary: 获取用户信息
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: 用户id
          type: string
          required: true
      tags:
        - Users
      responses:
        '200':
          description: 注册成功
          schema:
            $ref: '#/definitions/User'

definitions:
  Cert:
    type: object
    properties:
      companyType:
        type: integer
        description: 企业类型(0:电池厂商 1:汽车厂商)
      companyName:
        type: string
        description: 企业名称
      creditCode:
        type: string
        description: 社会信用码
      vendorCode:
        type: string
        description: 厂商代码
      contact:
        type: string
        description: 联系人
      phone:
        type: string
        description: 联系电话
      email:
        type: string
        description: 电子邮箱
      uploadCertName:
        type: string
        description: 上传的企业法人证书名称
      status:
        type: integer
        description: 申请证书的状态
    required:
      - companyType
      - companyName
      - creditCode
      - vendorCode
      - phone
      - email
      - uploadCertName
    example:
      companyType: 1
      companyName: "电池厂商1"
      creditCode: "91110108786172399R"
      vendorCode: "111111"
      contact: "张三"
      phone: "13728783627"
      email: "894738373@qq.com"
      uploadCertName: C:\user\demo.pdf
  Trac:
    type: object
    properties:
      productTime:
        type: date
        description: 生产日期
      productId:
        type: string
        description: 产品Id
      srcCompany:
        type: string
        description: 源厂商
      desCompany:
        type: string
        description: 目的厂商
      moduleId:
        type: string
        description: 模组编号
      packageId:
        type: string
        description: 包编号
      carId:
        type: string
        description: 车架编号
    required:
      - productTime
      - productId
      - srcCompany
      - desCompany
      - moduleId
      - packageId
      - carId
    example:
      productTime: "2016-11-1"
      productId: "1111111"
      srcCompany: "A电池厂商"
      desCompany: "B汽车销售厂商"
      moduleId: "AHUWGUU121334HUEU"
      packageId: "DHFJW7286442HJDHRFJ"
      carId: "1334"
  User:
    type: object
    properties:
      userName:
        type: string
        description: 手机号码
      password:
        type: string
        description: 密码
      createDate:
        type: string
        format: date
        description: 日期
      state:
        type: integer
        format: int32
        description: 状态
    required:
      - userName
      - password
    example:
      userName: "zhangsan"
      password: "justPass"
      createDate: "2016-01-01"
      state: 0
  Auth:
    type: object
    properties:
      phoneNumber:
        type: string
        description: 手机号码
      password:
        type: string
        description: 密码
    required:
      - phoneNumber
      - password
    example:
      phoneNumber: "18955555555"
      password: "justPass"

  Token:
    type: object
    properties:
      token:
        type: string
        description: 返回的token
      userId:
        type: integer
        format: int64
        description: 用户id
      userName:
        type: string
        description: 用户名
    example:
      token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MywiZXhwIjoxNDcwODI5NDk1LCJ1c2VyIjp7ImlkIjozLCJwYXNzd29yZCI6IjgxY2UyYmRjMTdlMjVmNWY0MjcyMWY1ZjEzYWU5NTYwODBjNzMzOGM4ZGYwODk2OTA4MDY5MzhmNmM3MjAyODEiLCJzYWx0IjoiNTRhOTQ0ZWUtZDRkYy00ZjcyLWE2N2EtNzBiZTE4ZDc3MjMxIiwicGhvbmVOdW1iZXIiOiIxOTk5OTk5OTk5IiwiY3JlYXRUaW1lIjpudWxsLCJ1cGRhdGVUaW1lIjpudWxsLCJwZXJzaXN0ZW50Ijp0cnVlLCJlbnRpdHlJZCI6M30sImlhdCI6MTQ3MDgyNTg5NX0.kwoSodGxS81HPWCiIydk0Z4Of6rljkR6hLAQ1VNeYhs"
      userId: 100
      userName: "18955555555"

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
        description: 参见 `ErrorCode` 中的定义
      message:
        type: string
        description: 错误描述
      detail:
        type: string
        description: 错误的详细信息
parameters:
  accessKeyIdParam:
    name: access_key_id
    in: query
    description: 访问密钥
    required: true
    type: string
  signatureVersionParam:
    name: signature_version
    in: query
    description: '签名函数的版本号,目前只支持版本号为 `1`,签名所用哈希算法为HmacSHA256'
    required: true
    type: number
    format: int32
    default: 1
  signatureParam:
    name: signature
    in: query
    description: 请求消息的签名
    required: true
    type: string